import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Simon Beyzerov</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* <h2>Bio</h2> */}
        <p>
          Hi! I'm Simon, a high school student curious about computer science and mathematics. 
          I love making stuff and exploring new ideas in both fields; I'm particularly excited by projects that combine ideas to tackle real problems in a novel way. 
        </p>
        <p>
          My research interests lie primarily in applied cryptography and theoretical computer science. 
          Check out my projects for a more detailed description.
        </p>
      </div>
    </>
  )
}
