import Head from 'next/head'
import Image from 'next/image'
import LazyShow from "/components/LazyShow";
import styled from 'styled-components';
import { Award, Svg100Award, Medal } from '/components/icons/index'
import { Tooltip, Button, Spacer, Collapse, Text, Grid, Link } from '@nextui-org/react';
import styles from '../styles/Projects.module.css'

import { motion, useAnimation } from "framer-motion"
import { useInView } from "react-intersection-observer";
import { useEffect } from "react";

const NoteItem = ({ children, title, mainIcon }) => (
  <>
      <Tooltip content={children} color="primary" style={{paddingLeft: ".3rem"}}>
        <div class="svgContainer">{mainIcon}</div>
      </Tooltip>
  </>
)
  

const ProjectTitle = ({ children, notes }) => (
  <div
  className={styles.hFlex}>
      <Text weight="medium" className={styles.projectTitle}>
        {children}
      </Text>
    <div className="noteContainer" style={{ flex: "1", display: "inline-block"}}>
      {notes.map((item,index)=>(
        <NoteItem mainIcon={item.displayIcon} title={item.title}>{item.description}</NoteItem>
      ))}
    </div>
  </div>
)

const ProjectItem = ({ title, children, notes=[], links=[] }) => (
  <div className={styles.projectItem}>
    <ProjectTitle notes={notes}>{title}</ProjectTitle>
    {children}
    <div className={styles.hFlex}>
      {
      links.map((item,index)=>(
        < >
        <Link href={item.url} target="_blank">
          <Button style={{height: '1.4rem', marginTop: ".4rem", fontSize: "0.8rem"}}
            auto rounded bordered
            >
              {item.title}
          </Button>
        </Link>
        <Spacer x={0.5}/>
        </>
      ))
      }
    </div>
  </div>
)


const ProjectItemCollapse = ({title, children, notes, links }) => {

  const control = useAnimation();
  const [ref, inView] = useInView();

  useEffect(() => {
    if (inView) {
      control.start("visible");
    } else {
      control.start("hidden");
    }
  }, [control, inView]);

  return <LazyShow
      >
        <Collapse
          title={
            <ProjectItem
              title={title}
              notes={notes}
              links={links}>
            </ProjectItem>
          }
          shadow={true}
          bordered={true}
          >
          <Text>
            {children}
          </Text>
        </Collapse>
      </LazyShow>
  
}

// {displayIcon: <Svg100Award/>, title: "", description: "1st Place Regeneron STS"},
// {displayIcon: <Award/>, title: "", description: "yesyesyes"}

export default function Projects() {
  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h2>Research</h2>
        <Grid.Container>
          <Grid>
            <Collapse.Group splitted>
              <ProjectItemCollapse 
                title="Private Access Control for Function Secret Sharing" 
                links={[{title: "Paper"}, {title: "Github"}]}>
                  Written in conjunction with MIT PRIMES. Cryptography paper developing distributed zero knowledge proof protocols towards access control for secret-shared functions.
              </ProjectItemCollapse> 


              <ProjectItemCollapse title="Cloak: A Versatile Framework for Anonymous Authentication" 
              links={[{title: "Paper"}, {title: "Github"}]}
              >
                Written in conjunction with MIT PRIMES. Cryptography paper developing privacy-preserving authentication through secret-shared ZK-proof protocols.
              </ProjectItemCollapse>

              <ProjectItemCollapse title="Authenticated Metadata-hiding Anonymous Communication" 
              links={[{title: "Paper"}, {title: "Github"}]}
              >
                Independent research paper exploring how anonymous authentication techniques can be used to improve the current state of the art in anonymous communication systems with cryptographic privacy guarantees. 
              </ProjectItemCollapse>

              <ProjectItemCollapse title="Key-Homomorphic Pseudorandom Functions from Learning with Errors" 
              links={[]}
              >
                (Still in the works!)
              </ProjectItemCollapse>

              <ProjectItemCollapse title="Moderately Hard Functions: A new cost model" 
              links={[]}
              >
                (Still in the works!)
              </ProjectItemCollapse>   
                
            </Collapse.Group>
          </Grid>
        </Grid.Container>
        
        
      </div>
      <div>
      <h2>Other cool projects</h2>

      <Grid.Container>
          <Grid>
            <Collapse.Group splitted>
            <ProjectItemCollapse title="SigmaML" 
            links={[{title: "Github"}]}
            >
              A cross-platform desktop application for building machine learning models, aggregating all steps of the development process. Built with web-based technology: JavaScript, Svelte, Electron, Python.
            </ProjectItemCollapse>
            <ProjectItemCollapse title="Mealgo: Recipe Filtering" 
            links={[{title: "Poster"}, {title: "Github"}]}
            >
              
            </ProjectItemCollapse>
            <ProjectItemCollapse title="NaVi: Aid for Independent Navigation for the Visually Impaired" 
            links={[{title: "Poster"}]}
            >
              
            </ProjectItemCollapse>
            <ProjectItemCollapse title="IMMC" 
            notes={[{displayIcon: <Award/>, title: "", description: "Awarded US Regional Finalist"}]}
            links={[{title: "Paper"}]}>
            </ProjectItemCollapse>
            <ProjectItemCollapse title="HiMCM" 
            notes={[{displayIcon: <Award/>, title: "", description: "Awarded Meritorious"}]}
            links={[{title: "Paper"}]}>
            </ProjectItemCollapse>
            <ProjectItemCollapse title="MathWorks" 
            notes={[{displayIcon: <Award/>, title: "", description: "Advanced to Second Round of Competition (Top ~100 papers)"}]}
            links={[{title: "Paper"}]}>
            </ProjectItemCollapse>  
                
            </Collapse.Group>
          </Grid>
        </Grid.Container>


        
      </div>
    </>
  )
}
